Separate the ALTREP constructor for vectors.
extendr/extendr pull request #401
Opened 2022-05-03 13:28 UTC by andy-thomason

Before this change, vector constructors require many bounds on the iterator.

This is still true of ALTREP constructors, but the regular `from_values` is now
much simpler.

Explicit allocated vector.

```
        let vec = Doubles::from_values((0..3).map(|i| 2.0 - i as f64));
        assert_eq!(vec.is_altrep(), false);
        assert_eq!(r!(vec.clone()), r!([2.0, 1.0, 0.0]));
        assert_eq!(vec.elt(1), 1.0);
        let mut dest = [0.0.into(); 2];
        vec.get_region(1, &mut dest);
        assert_eq!(dest, [1.0, 0.0]);
```

Explicit ALTREP vector.

```
        let vec = Doubles::from_values_altrep((0..1000000000).map(|x| x as f64));
        assert_eq!(vec.is_altrep(), true);
        assert_eq!(vec.elt(12345678), 12345678.0);
        let mut dest = [0.0.into(); 2];
        vec.get_region(12345678, &mut dest);
        assert_eq!(dest, [12345678.0, 12345679.0]);
```

2022-05-17 10:28 UTC, andy-thomason commented
If no one objects, I'm just going to merge this.

2022-05-17 10:31 UTC, Ilia-Kosenkov commented
If you want a thouroug review, I need some extra time. Otherwise, feel free to merge though I am concerned about failed CIs.

2022-05-17 10:53 UTC, andy-thomason commented
I'll look at the tests. Looks like the very large vector is allocated in memory, which is not good!

2022-05-17 11:26 UTC, multimeric requested changes
Should really add a test for the base `X::from_values()` method.

2022-05-17 12:59 UTC, andy-thomason commented
Down to an ephemeral failure in test_altreal.

In theory everything is protected by single_threaded, if this persists. I'll take a deeper look.

2022-05-17 13:55 UTC, andy-thomason commented
The original `from_values` tests should be unchanged, but I've renamed some of them to `from_values_altrep`.

2022-05-17 14:04 UTC, multimeric approved these changes
Oh yes, I see the tests. They just didn't come up in the diff.

2022-05-17 15:04 UTC, Ilia-Kosenkov approved these changes

2022-05-17 15:17 UTC, merged

2022-05-19 10:22 UTC, andy-thomason commented
Oops, mea culpa.

> I think you managed to put your data frame derive commits into this branch before you merged, which isn't ideal.