Document how to make modules available to R packages
extendr/extendr pull request #461
Opened 2023-01-25 14:45 UTC by JosiahParry

This PR adds documentation to `extendr_module` to describe how to make module functions available to R 

Per https://discord.com/channels/751419551132155925/751419551132155928/1067806341491609772

2023-01-28 07:14 UTC, multimeric commented
The only thing I'm worried about here is recommending that they `use submodule` in the `#[extendr]` block rather than just asking them to `use submodule` in normal Rust and then defining the entire extendr module in one place. Would that not be simpler and cleaner?

Also, could you please pull from master please @JosiahParry?

2023-02-05 22:03 UTC, sorhawell commented
From discussion it appears to me that the consensus is now, that extendr-modules are an ok pattern.
https://discord.com/channels/751419551132155925/800474459630731335/1071355741950197770

The need for `use utils::get_utils_metadata;` might soon be obsolete with #469, but no harms done if not updated immediately when #469 merges.

I think this brings value as is.

2023-02-05 22:07 UTC, multimeric approved these changes

2023-02-06 13:28 UTC, JosiahParry commented
That should be fixed now.

2023-02-06 14:09 UTC, JosiahParry commented
The failed CI runs are due to upstream error in ubuntu 20.04 r-lib action.

2023-02-09 10:37 UTC, CGMossa approved these changes
I approve of this, but the metadata part needs to be removed. As soon as my PR is merged we can do that.

2023-02-09 15:37 UTC, JosiahParry commented
@CGMossa removed the note about get_{mod}_metadata

2023-02-12 20:52 UTC, CGMossa commented on extendr-macros/src/lib.rs
> +/// use utils::get_utils_metadata;
this needs to be removed as well

2023-02-12 20:53 UTC, CGMossa commented
I *think* one module has to act as the a "root" though. But I'm unsure...

2023-02-25 03:55 UTC, multimeric requested changes
This is basically good to go, but please add a changelog entry under a "Unreleased" title, using the `[docs]` tag. This won't be in the next release but we need to get in the habit of updating the changelog.

2023-05-01 13:58 UTC, closed without merging