Fix unused_mut warning
extendr/extendr pull request #641
Opened 2023-10-06 13:41 UTC by yutannihilation

I see this warning:

```
warning: variable does not need to be mutable
   --> src\wrapper\strings.rs:112:13
    |
112 |         let mut robj = Strings::alloc_vector(STRSXP, len);
    |             ----^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default
```

2023-10-06 13:48 UTC, CGMossa requested changes
This shows that `extendr` is unsound. We need to deal with that everywhere. I'd like this warning to stay please.

2023-10-06 13:51 UTC, yutannihilation commented
Do you mean this should actually require `mut`? If so, I just close this pull request.

2023-10-06 14:04 UTC, CGMossa commented
Yes!

We create a vector here that we fill out. Usually, you need a `&mut` to do
so.
But `GetSexp` only has a `get(&self)`, while it should in fact also carry a
`get_mut(&mut self)`,
that is then fed into `SET_STRING_ELT`. This is how we unsafely pass around
a pointer,
but ensure exclusive-access is maintained properly.

I've tried a few times to add this, and now that I'm working on the
`OwnedRobj`/`PermanentRobj`/`RawRobj` PR, I might figure out how to add
this properly.



On Fri, Oct 6, 2023 at 3:51 PM Hiroaki Yutani ***@***.***>
wrote:

> Do you mean this should actually require mut? If so, I just close this
> pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/extendr/extendr/pull/641#issuecomment-1750718043>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIDVSBHCDVN4OBR56O3BTTX6AEHTAVCNFSM6AAAAAA5V3DUHGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJQG4YTQMBUGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-10-06 14:04 UTC, CGMossa commented
Yes!

We create a vector here that we fill out. Usually, you need a `&mut` to do
so.
But `GetSexp` only has a `get(&self)`, while it should in fact also carry a
`get_mut(&mut self)`,
that is then fed into `SET_STRING_ELT`. This is how we unsafely pass around
a pointer,
but ensure exclusive-access is maintained properly.

I've tried a few times to add this, and now that I'm working on the
`OwnedRobj`/`PermanentRobj`/`RawRobj` PR, I might figure out how to add
this properly.

2023-10-07 00:11 UTC, yutannihilation commented
Okay, I don't feel it really matters whether this `mut` is left or not, but let's close now. Thanks for sharing.

2023-10-07 00:11 UTC, closed without merging