Add `PartialEq` for `Rstr`
extendr/extendr pull request #845
Opened 2024-09-05 22:08 UTC by CGMossa

addition: It is not possible to compare `Rstr` to 
`Rstr` like the R interpreter does.

2024-09-06 07:33 UTC, CGMossa commented
Okay, so what the changes here enable, is to use R's string-interner, as part of `Rstr`, to make them efficiently comparable.
I believe before it would be _slower_ to compare `Rstr` than it is to compare `&str`, which is unintuitive.

Let me illustrate the full case here: Let us make an function that finds the total number of unique character strings in a `character()`-vector. Currently, we offer two interfaces, the native-adjacent `Rstr` and the Rust native `&str`. 

```rs
use extendr_api::prelude::*;

#[extendr]
fn to_unique_rstr(r_char_vec: Strings) -> usize {
    let capacity = r_char_vec.len();
    let mut seen: Vec<&Rstr> = Vec::with_capacity(capacity);
    let mut n_unique = 0;
    for word in r_char_vec.iter() {
        if !seen.contains(&word) {
            n_unique += 1;
            seen.push(word);
        }
    }
    n_unique
}

#[extendr]
fn to_unique_str(r_char_vec: StrIter) -> usize {
    let capacity = r_char_vec.len();
    let mut seen: Vec<&str> = Vec::with_capacity(capacity);
    let mut n_unique = 0;
    for word in r_char_vec {
        if !seen.contains(&word) {
            n_unique += 1;
            seen.push(word);
        }
    }
    n_unique
}
```

These two implementations are **identical**, except for their different string type.
But their performance is certainly not identical:

```r
library(magrittr)
library(tidyverse)
devtools::load_all(path = "tests/extendrtests")

text_character_vector <-
  lorem::ipsum_words(1e6, collapse = FALSE)

to_unique_rstr(text_character_vector)
to_unique_str(text_character_vector)


bench::mark(
  # dplyr = dplyr::n_distinct(text_character_vector),
  rstr = to_unique_rstr(text_character_vector),
  str = to_unique_str(text_character_vector),
  check = TRUE
) -> bm_n_unique

bm_n_unique %>% 
  select(expression, is.atomic)
# # A tibble: 2 × 9
# expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
# <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
# 1 rstr          539ms    539ms      1.86        0B        0     1     0      539ms
# 2 str           840ms    840ms      1.19        0B        0     1     0      840ms
```

Thus, it is twice as fast to "compare" `Rstr` than it is to compare `&str`.

2024-10-26 16:46 UTC, JosiahParry requested changes

2024-10-26 16:46 UTC, JosiahParry commented on extendr-api/src/iter.rs
> +impl TryFrom<Robj> for StrIter {
Can we add a doc comment here? I'm not sure where this may be used or really how.

2024-10-26 16:46 UTC, JosiahParry commented on extendr-api/src/wrapper/rstr.rs
> +impl PartialEq<Rstr> for Rstr {
```suggestion
/// Utilize SEXP for comparison of [`Rstr`]
/// Deferring to R's comparison results in faster comparisons.
impl PartialEq<Rstr> for Rstr {
```

2024-10-26 16:46 UTC, JosiahParry commented on extendr-api/src/wrapper/rstr.rs
> +impl PartialEq<Rstr> for &str {
```suggestion
// casts Rstr to a string slice for comparison
// less efficient than comparing two [Rstr]
impl PartialEq<Rstr> for &str {
```

2024-10-26 16:46 UTC, JosiahParry commented on tests/extendrtests/notebooks/001_create_unique_vectors.R
i think this file is accidentally committed?

2024-10-26 17:19 UTC, JosiahParry approved these changes
Once we get CI to pass let's merge this. This is a huge performance boost.

2024-10-26 18:03 UTC, JosiahParry commented
CI is not passing due to the macro snapshot tests. The macro expansion snapshots do not appear to be identical across distro / rust version matrix.

I do not see how to fix this for the PR.

2024-10-26 18:31 UTC, JosiahParry commented
I'm going to merge this PR the current failing issues are due to an issue in R-devel https://bugs.r-project.org/show_bug.cgi?id=18806.

I have a patch to address this but it is being ignored.

2024-10-26 18:31 UTC, merged